apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    com.centurylinklabs.watchtower.scope: cobalt
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: cobalt-api
  name: cobalt-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cobalt-api
  template:
    metadata:
      annotations:
        com.centurylinklabs.watchtower.scope: cobalt
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: cobalt-api
    spec:
      containers:
        - env:
            - name: API_URL
              value: http://cobalt-api:9000/
          image: ghcr.io/imputnet/cobalt:10
          name: cobalt-api
          ports:
            - containerPort: 9000
              protocol: TCP
      restartPolicy: Always
