apiVersion: v1
kind: Service
metadata:
  annotations:
    com.centurylinklabs.watchtower.scope: cobalt
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: cobalt-api
  name: cobalt-api
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: cobalt-api
