apiVersion: apps/v1
kind: Deployment
metadata:
  # ADDITION: Specify the namespace to ensure it's deployed in the right place.
  namespace: alexbot
  name: cobalt-api
  # ADDITION: Add labels to the Deployment itself for better organization.
  labels:
    app: cobalt-api
spec:
  replicas: 1
  # ADDITION: The selector tells the Deployment which Pods to manage.
  # It MUST match the labels of the Pod template below.
  selector:
    matchLabels:
      app: cobalt-api
  template:
    metadata:
      # ADDITION: Add labels to the Pods. This is how the Service and Deployment find them.
      labels:
        app: cobalt-api
    spec:
      containers:
        - name: cobalt-api
          image: ghcr.io/imputnet/cobalt:10
          env:
            - name: API_URL
              value: http://cobalt-api:9000/
          ports:
            - containerPort: 9000
              protocol: TCP
          # ADDITION: Probes help Kubernetes understand the health of your application.
          livenessProbe:
            httpGet:
              # This path should return a 200 OK status if the app is healthy.
              path: /
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              # This path tells Kubernetes when the app is ready to receive traffic.
              path: /
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          # ADDITION: Resource requests and limits are crucial for cluster stability.
          resources:
            requests:
              # The minimum amount of resources the container needs.
              cpu: "100m" # 0.1 CPU core
              memory: "128Mi" # 128 Mebibytes
            limits:
              # The maximum amount of resources the container can use.
              cpu: "500m" # 0.5 CPU core
              memory: "256Mi" # 256 Mebibytes
      # NOTE: restartPolicy: Always is the default for Deployments, so it can be omitted.