apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: longhorn-backup-secret
  namespace: longhorn-system
spec:
  itemPath: "vaults/ptjje7jpatl54g3y4sgwsnlyge/items/xg2qpoyk6zwrnfr2jqp3bsdifi"
