apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: longhorn-backup-secret
  namespace: longhorn-system # This should be in the same namespace as Longhorn
spec:
  itemPath: "vaults/ptjje7jpatl54g3y4sgwsnlyge/items/xg2qpoyk6zwrnfr2jqp3bsdifi"
  # Define how to map 1Password item fields to Kubernetes Secret keys
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      field: username
    - secretKey: AWS_SECRET_ACCESS_KEY
      field: password
    # Longhorn's S3 backup often requires an endpoint. 
    # This might be configured via the 'backupTarget' URL directly in the Helm values,
    # or sometimes as an environment variable in the secret.
    # If a custom endpoint is needed in the secret, uncomment and adjust the following:
    # - secretKey: AWS_ENDPOINTS
    #   field: endpoint # Assuming 'endpoint' is a field in your 1Password item
