apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: leantime-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gissilabs.github.io/charts
    chart: leantime
    targetRevision: 1.3.0
    helm:
      values: |
        # Internal Database (MariaDB)
        internalDatabase:
          enabled: true
          existingSecret: leantime-secrets # Expects keys: database-root, database-user, database-password
          persistence:
            enabled: true
            storageClass: longhorn
            size: 5Gi
        
        leantime:
          url: https://tasks.kbrt.xyz
          existingSecret: leantime-secrets # Expects key: session-salt
          
          # Debugging
          extraEnv:
            LEAN_DEBUG: "1"
            LEAN_OIDC_DEBUG: "1"
            LEAN_OIDC_CREATE_USER: "true"
            LEAN_OIDC_DEFAULT_ROLE: "40"
            LEAN_DEFAULT_TIMEZONE: "America/Anchorage"
            LEAN_OIDC_FIELD_EMAIL: "email"
            LEAN_OIDC_SCOPES: "openid profile email"

          # S3 Config (Backblaze B2)
          s3:
            enabled: true
            endpoint: https://s3.us-west-004.backblazeb2.com
            region: us-west-004
            bucket: assets-6a939b
            usePathStyleEndpoint: false
            existingSecret: leantime-secrets # Expects keys: s3-key, s3-secret
          
          # SMTP Config
          smtp:
            enabled: true
            from: "Leantime <tasks@kbrt.xyz>"
            host: smtp.fastmail.com
            auth: true
            port: 465
            secureProtocol: ssl
            existingSecret: leantime-secrets # Expects keys: smtp-user, smtp-password
          
          # OIDC Config
          oidc:
            enabled: true
            createUser: true
            providerUrl: https://id.kbrt.xyz/application/o/lean-time/
            existingSecret: leantime-secrets # Expects keys: oidc-client-id, oidc-client-secret
            # Fix for nil pointer in chart template
            overrides:
              fields: {}

        # Deployment Strategy
        strategy:
          type: Recreate

        # Ingress (Disabled in chart, provided manually)
        ingress:
          enabled: false
        
        # Persistence for user files
        persistence:
          enabled: true
          storageClass: longhorn
          size: 5Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: leantime
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
