apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: leantime-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gissilabs.github.io/charts
    chart: leantime
    targetRevision: 1.0.8
    helm:
      values: |
        # Internal Database (MariaDB)
        # We let the chart auto-generate the credentials and secret for this.
        internalDatabase:
          enabled: true
          persistence:
            enabled: true
            storageClass: longhorn
            size: 5Gi
        
        leantime:
          url: https://tasks.kbrt.xyz
          
          # S3 Config (Backblaze B2)
          s3:
            enabled: true
            endpoint: https://s3.us-west-004.backblazeb2.com
            region: us-west-004
            bucket: assets-6a939b
            usePathStyleEndpoint: false
            existingSecret: leantime-secrets # Expects keys: s3-key, s3-secret
          
          # SMTP Config
          smtp:
            enabled: true
            host: smtp.mailgun.org # We still need to provide a host, or map it if it's in the secret (chart doesn't map host from secret by default, only user/pass)
            # Actually, the user's secret had smtp-host. The chart might not read it from secret automatically.
            # Let's re-add the extraEnv for the things that existingSecret MIGHT not cover, 
            # OR just map the host here if we know it.
            # For safety, I'll keep the extraEnv for the host and from address if the chart doesn't support secret mapping for those.
            # Checking values: existingSecret keys are 'smtp-user' and 'smtp-password'. 
            # It does NOT cover 'host' or 'from'.
            auth: true
            port: 465
            secureProtocol: ssl
            existingSecret: leantime-secrets # Expects keys: smtp-user, smtp-password
          
          # OIDC Config
          oidc:
            enabled: true
            providerUrl: https://id.kbrt.xyz/application/o/leantime/
            existingSecret: leantime-secrets # Expects keys: oidc-client-id, oidc-client-secret

          # Environment variable overrides for things not covered by existingSecret
          extraEnv:
            - name: LEANTIME_SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: leantime-secrets
                  key: smtp-host
            - name: LEANTIME_SMTP_FROM
              valueFrom:
                secretKeyRef:
                  name: leantime-secrets
                  key: smtp-from

        # Ingress
        ingress:
          enabled: true
          className: traefik
          host: tasks.kbrt.xyz
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
        
        # Persistence for user files
        persistence:
          enabled: true
          storageClass: longhorn
          size: 5Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: leantime
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
