apiVersion: v1
kind: Namespace
metadata:
  name: actual-budget
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: actual-budget-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
    volumeHandle: actual-budget-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-data-new
  namespace: actual-budget
  labels:
    # Pick up automated S3 backups
    recurring-job-group.longhorn.io/default: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
  volumeName: actual-budget-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual-server
  namespace: actual-budget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actual-server
  template:
    metadata:
      labels:
        app: actual-server
    spec:
      containers:
        - name: actual-server
          image: docker.io/actualbudget/actual-server:latest
          ports:
            - containerPort: 5006
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /
              port: 5006
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 5006
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: actual-data-new
---
apiVersion: v1
kind: Service
metadata:
  name: actual-server
  namespace: actual-budget
spec:
  ports:
    - port: 80
      targetPort: 5006
  selector:
    app: actual-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: actual-ui
  namespace: actual-budget
  annotations:
    tailscale.com/hostname: "actual"
    tailscale.com/https: "true"
    tailscale.com/tags: "tag:deployment"
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - actual.moose-amberjack.ts.net
  rules:
  - host: actual.moose-amberjack.ts.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: actual-server
            port:
              number: 80