apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # The application is named 'argocd', managing resources in the 'argocd' namespace
  name: argocd
  namespace: argocd
spec:
  project: default

  # Source of truth is the official Argo CD Helm chart
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 6.11.1 # Pinning to a specific version for consistency
    helm:
      values: |
        # All of Argo CD's configuration can be managed here
        # For example, you can add extra config, manage projects, etc.
        server:
          config:
            # Example: Disable the built-in admin user after setting up SSO
            "admin.enabled": "false"

  # Destination is the same cluster and namespace where Argo CD is running
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true