# k3s/argo-cd/argo-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    # This tells Traefik that the ArgoCD service communicates over HTTPS
    traefik.ingress.kubernetes.io/protocol: "https"
spec:
  # This ensures your Traefik controller handles this Ingress
  ingressClassName: traefik
  rules:
    # The MagicDNS hostname you want to use
  - host: argo.moose-amberjack.ts.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # The name of the Argo CD server service
            name: argocd-server
            port:
              # The HTTPS port for the Argo CD UI
              name: https