apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-synapse
  namespace: matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matrix-synapse
  template:
    metadata:
      labels:
        app: matrix-synapse
    spec:
      securityContext:
        fsGroup: 991
        fsGroupChangePolicy: "OnRootMismatch"

      initContainers:
        # 1. Install S3 Provider Module
        - name: install-s3-lib
          image: matrixdotorg/synapse:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              pip install --target /modules boto3 tqdm
              pip install --target /modules --no-deps https://github.com/matrix-org/synapse-s3-storage-provider/archive/refs/heads/main.zip
          volumeMounts:
            - name: python-modules
              mountPath: /modules

        # 2. Build Config (Substitutions)
        - name: config-builder
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Read secrets
              DB_PASS=$(cat /secrets/db/password)
              REG_SECRET=$(cat /secrets/matrix/SYNAPSE_REGISTRATION_SHARED_SECRET)
              MAC_SECRET=$(cat /secrets/matrix/SYNAPSE_MACAROON_SECRET_KEY)
              S3_ACCESS=$(cat /secrets/s3/AWS_ACCESS_KEY_ID)
              S3_SECRET=$(cat /secrets/s3/AWS_SECRET_ACCESS_KEY)
              
              # Copy template
              cp /config-template/homeserver.yaml /data/homeserver.yaml
              
              # Substitute
              sed -i "s|DB_PASSWORD_PLACEHOLDER|$DB_PASS|g" /data/homeserver.yaml
              sed -i "s|REGISTRATION_SECRET_PLACEHOLDER|$REG_SECRET|g" /data/homeserver.yaml
              sed -i "s|MACAROON_SECRET_PLACEHOLDER|$MAC_SECRET|g" /data/homeserver.yaml
              sed -i "s|ACCESS_KEY_PLACEHOLDER|$S3_ACCESS|g" /data/homeserver.yaml
              sed -i "s|SECRET_KEY_PLACEHOLDER|$S3_SECRET|g" /data/homeserver.yaml
              
              # Copy signing key
              if [ -f /secrets/matrix/SYNAPSE_SIGNING_KEY ]; then
                cp /secrets/matrix/SYNAPSE_SIGNING_KEY /data/signing.key
                chmod 644 /data/signing.key
              fi

          volumeMounts:
            - name: config-template
              mountPath: /config-template
            - name: generated-config
              mountPath: /data
            - name: matrix-secrets
              mountPath: /secrets/matrix
            - name: db-secret
              mountPath: /secrets/db
            - name: s3-secret
              mountPath: /secrets/s3

      containers:
        # --- Synapse ---
        - name: synapse
          image: matrixdotorg/synapse:latest
          args: ["run"]
          env:
            - name: PYTHONPATH
              value: "/modules"
          ports:
            - containerPort: 8008
              name: http
          volumeMounts:
            - name: generated-config
              mountPath: /data
            - name: media-store
              mountPath: /data/media_store
            - name: python-modules
              mountPath: /modules
          livenessProbe:
            httpGet:
              path: /health
              port: 8008
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8008
            initialDelaySeconds: 15
            periodSeconds: 10
        
        # --- Sliding Sync Proxy (Element X) ---
        - name: sliding-sync
          image: ghcr.io/matrix-org/sliding-sync:latest
          env:
            - name: SYNCV3_SERVER
              value: "http://localhost:8008"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: matrix-db-app
                  key: password
            - name: SYNCV3_DB
              value: "postgres://synapse:$(DB_PASSWORD)@matrix-db-rw.matrix.svc/synapse?sslmode=disable"
            - name: SYNCV3_SECRET
              valueFrom:
                secretKeyRef:
                  name: matrix-secrets
                  key: SLIDING_SYNC_SECRET
            - name: SYNCV3_BINDADDR
              value: "0.0.0.0:8009"
          ports:
            - containerPort: 8009
              name: sync

      volumes:
        - name: config-template
          configMap:
            name: matrix-config
        - name: generated-config
          emptyDir: {}
        - name: media-store
          emptyDir: {}
        - name: python-modules
          emptyDir: {}
        - name: matrix-secrets
          secret:
            secretName: matrix-secrets
        - name: db-secret
          secret:
            secretName: matrix-db-app
        - name: s3-secret
          secret:
            secretName: backblaze-app-key-secret
---
apiVersion: v1
kind: Service
metadata:
  name: matrix
  namespace: matrix
spec:
  ports:
    - port: 80
      targetPort: 8008
      name: http
    - port: 8009
      targetPort: 8009
      name: sync
  selector:
    app: matrix-synapse
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matrix
  namespace: matrix
spec:
  rules:
  - host: matrix.kbrt.xyz
    http:
      paths:
      # MAS Routes
      - path: /.well-known/openid-configuration
        pathType: Prefix
        backend:
          service:
            name: mas
            port:
              number: 8080
      - path: /_matrix/oidc
        pathType: Prefix
        backend:
          service:
            name: mas
            port:
              number: 8080
      - path: /_matrix/client/v3/login
        pathType: Prefix
        backend:
          service:
            name: mas
            port:
              number: 8080
      - path: /_matrix/client/v3/logout
        pathType: Prefix
        backend:
          service:
            name: mas
            port:
              number: 8080
      - path: /_matrix/client/v3/refresh
        pathType: Prefix
        backend:
          service:
            name: mas
            port:
              number: 8080
      
      # Synapse Routes
      - path: /
        pathType: Prefix
        backend:
          service:
            name: matrix
            port:
              number: 80
      
      # Sliding Sync Routes
      - path: /_matrix/client/unstable/org.matrix.msc3575/sync
        pathType: Prefix
        backend:
          service:
            name: matrix
            port:
              number: 8009
      - path: /client/server.json
        pathType: Prefix
        backend:
          service:
            name: matrix
            port:
              number: 8009