apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-db
  namespace: matrix
spec:
  instances: 1
  enableSuperuserAccess: true
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  bootstrap:
    initdb:
      database: synapse
      owner: synapse
  storage:
    storageClass: longhorn-postgres
    size: 5Gi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: backblaze-b2-store
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: matrix-db-daily-backup
  namespace: matrix
spec:
  schedule: "0 4 * * *"
  backupOwnerReference: cluster
  cluster:
    name: matrix-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: backblaze-b2-store
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: backblaze-b2-store
  namespace: matrix
spec:
  configuration:
    destinationPath: "s3://k3s-backup-7cabee/matrix-v2/"
    endpointURL: "https://s3.us-west-004.backblazeb2.com"
    s3Credentials:
      accessKeyId:
        name: backblaze-app-key-secret
        key: username
      secretAccessKey:
        name: backblaze-app-key-secret
        key: password
    wal:
      compression: gzip
      maxParallel: 1
    data:
      compression: gzip
      jobs: 2
  retentionPolicy: "30d"
