apiVersion: batch/v1
kind: Job
metadata:
  name: mas-db-init
  namespace: matrix
spec:
  template:
    spec:
      containers:
        - name: psql
          image: postgres:17-alpine@sha256:3430fe182f5065a6ea505c3d432d2c7fff18fbab954df8f277c1dbf4c70124af
          command: ["/bin/sh", "-c"]
          args:
            - |
              export PGPASSWORD=$SUPER_PASS
              echo "Waiting for database to be ready..."
              until psql -h matrix-db-rw.matrix.svc -U postgres -c "SELECT 1;" > /dev/null 2>&1; do
                sleep 2
              done
              
              if psql -h matrix-db-rw.matrix.svc -U postgres -lqt | cut -d \| -f 1 | grep -qw mas; then
                echo "Database 'mas' already exists."
              else
                echo "Creating database 'mas'..."
                psql -h matrix-db-rw.matrix.svc -U postgres -c "CREATE USER mas WITH PASSWORD '$DB_PASS';"
                psql -h matrix-db-rw.matrix.svc -U postgres -c "CREATE DATABASE mas OWNER mas;"
              fi
          env:
            - name: SUPER_PASS
              valueFrom:
                secretKeyRef:
                  name: matrix-db-superuser
                  key: password
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: matrix-db-app
                  key: password
      restartPolicy: OnFailure
