apiVersion: v1
kind: ConfigMap
metadata:
  name: element-web-config
  namespace: matrix
data:
  config.json: |
    {
        "default_server_config": {
            "m.homeserver": {
                "base_url": "https://matrix.kbrt.xyz",
                "server_name": "kbrt.xyz"
            },
            "m.identity_server": { "base_url": "https://vector.im" }
        },
        "brand": "KBRT Chat",
        "show_labs_settings": true,
        "features": { "feature_sliding_sync": true },
        "default_theme": "dark"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: element-web
  namespace: matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: element-web
  template:
    metadata:
      labels:
        app: element-web
    spec:
      containers:
        - name: element-web
          image: vectorim/element-web:latest@sha256:827ae9ebea5ec0eeb487660f4f04e5789b666667f17a0d63b5c0e4ad8b9b9ca1
          env:
            - { name: PORT, value: "80" }
            - { name: ELEMENT_WEB_PORT, value: "80" }
          ports:
            - containerPort: 80
          volumeMounts:
            - { name: config, mountPath: /app/config.json, subPath: config.json }
      volumes:
        - { name: config, configMap: { name: element-web-config } }
---
apiVersion: v1
kind: Service
metadata:
  name: element-web
  namespace: matrix
spec:
  ports:
    - { port: 80, targetPort: 80 }
  selector:
    app: element-web
