apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2025.12.4
    helm:
      values: |
        fullnameOverride: authentik
        
        # Disable bundled components
        redis:
          enabled: false
        postgresql:
          enabled: false
        
        authentik:
          # Use global env vars for everything to ensure bootstrap sees them
          postgresql:
            host: authentik-db-rw.authentik.svc
            name: authentik
            user: authentik
          
          email:
            port: 465
            use_ssl: true

        global:
          env:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: secret_key
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-db-app
                  key: password
            - name: AUTHENTIK_EMAIL__HOST
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: smtp_host
            - name: AUTHENTIK_EMAIL__FROM
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: smtp_from
            - name: AUTHENTIK_EMAIL__USERNAME
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: smtp_username
            - name: AUTHENTIK_EMAIL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: smtp_password

        server:
          ingress:
            enabled: true
            ingressClassName: tailscale
            annotations:
              tailscale.com/hostname: "id"
              tailscale.com/https: "true"
              tailscale.com/tags: "tag:deployment"
            hosts:
              - id.kbrt.xyz
            tls:
              - hosts:
                  - id.kbrt.xyz

  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
