apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: https-proxy
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        env:
          - name: TS_HTTPS_PORT
            value: "443"
