# k3s/tailscale/tailscale-operator.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: 1.94.1
    helm:
      values: |
        operator:
          oauth:
            # We are using the default secret name, but we still need to
            # map the keys from our 1Password item.
            # secretName: operator-oauth # This line is optional since it's the default
            clientIDKey: username
            clientSecretKey: password
          # Explicitly set the tags for the operator and managed nodes
          hostname: tailscale-operator
          logging: info
        proxyConfig:
          defaultTags:
            - tag:deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
            syncOptions:
              - CreateNamespace=true
              - ServerSideApply=true
              - Replace=true
        