apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
spec:
  # TODO: Update this with the actual 1Password item path for your tunnel token
  itemPath: "vaults/ptjje7jpatl54g3y4sgwsnlyge/items/22sgidqxpqrz6wb55jldqy5cqu"
