# argo-cd/onepassword-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-connect
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://1password.github.io/connect-helm-charts/'
    chart: connect
    targetRevision: 1.15.1 # Using the version from your latest attempt
    helm:
      values: |
        connect:
          create: true
          # Explicitly tell the chart which secret to use for the volume
          credentialsName: op-credentials
          
          # This is the critical fix: It forces the chart to mount the secret as a file.
          api:
            extraVolumeMounts:
            - name: credentials
              mountPath: "/home/opuser/.op/1password-credentials.json"
              subPath: "1password-credentials.json"
              readOnly: true
          sync:
            extraVolumeMounts:
            - name: credentials
              mountPath: "/home/opuser/.op/1password-credentials.json"
              subPath: "1password-credentials.json"
              readOnly: true
        
        operator:
          create: true
          # This correctly configures the operator to use its token
          token:
            name: onepassword-operator-token
            
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: onepassword
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
