# argo-cd/onepassword-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-connect
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://1password.github.io/connect-helm-charts/'
    chart: connect
    targetRevision: 1.15.1 # Or the latest version
    helm:
      values: |
        # Enable the Connect server
        connect:
          create: true
        # Enable the Operator
        operator:
          create: true
          # Tell the operator where to find its token
          token:
            # This references the onepassword-operator-token secret you created
            name: onepassword-operator-token
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: onepassword
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true