apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alex-bot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/xela-zone/k3s.git
    
    path: alexbot 
    
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    
    namespace: alexbot
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true