apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.4.4
    helm:
      values: |
        configs:
          cm:
            # Enable anonymous access
            "users.anonymous.enabled": "true"
            # Explicitly disable admin user to prevent confusion
            "admin.enabled": "false"
          rbac:
            # Grant admin privileges to the anonymous user
            "policy.default": "role:admin"
          params:
            # Insecure mode (disable TLS on the API server pod itself)
            "server.insecure": "true"
        server:
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
