apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: leantime
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/xela-zone/k3s.git
    path: leantime
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: leantime
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
