apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/xela-zone/k3s.git
    path: longhorn
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
