apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    targetRevision: 1.11.0
    chart: longhorn
        image:
          manager:
            tag: v1.11.0-hotfix-1
          instanceManager:
            tag: v1.11.0-hotfix-1
        upgradeVersionCheck: false
        metrics:
          serviceMonitor:
            enabled: true
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 1
        defaultSettings:
          backupTarget: s3://k3s-backup-7cabee@us-west-004/longhorn-backup/
          backupTargetCredentialSecret: longhorn-backup-secret
          replicaAutoBalance: "least-effort"
          defaultReplicaCount: 1
          createDefaultDiskAndNode: true
        preUpgradeChecker:
          jobEnabled: false
        s3:
          endpoint: https://s3.us-west-004.backblazeb2.com
        serviceAccount:
          annotations:
            argocd.argoproj.io/sync-wave: "-1"
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
