apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    targetRevision: 1.11.0 # Use a specific version, check for latest stable
    chart: longhorn
    helm:
      values: |
        persistence:
          defaultClass: true
        defaultSettings:
          backupTarget: s3://k3s-backup-7cabee/longhorn-backup/
          backupTargetCredentialSecret: longhorn-backup-secret
          replicaAutoBalance: "least-effort"
          defaultReplicaCount: 1 # Set replica count to 1 for single-node deployments
          createDefaultDiskAndNode: true # Ensure default disk and node are created
        preUpgradeChecker:
          jobEnabled: false
        s3:
          endpoint: https://s3.us-west-004.backblazeb2.com
        serviceAccount:
          annotations:
            argocd.argoproj.io/sync-wave: "-1"
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
