apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: ghcr.io/element-hq/ess-helm
      chart: matrix-stack
      targetRevision: 26.2.1
      helm:
        valueFiles:
          - $values/matrix/values.yaml
        parameters:
          - name: synapse.postgres.password.value
            value: "P5sYQ1eOCRpZtjN3XE7ni84IjNrBVGfSDNQU5oNz40glsVHFywt1CfURWowVQzNa"
          - name: matrixAuthenticationService.postgres.password.value
            value: "P5sYQ1eOCRpZtjN3XE7ni84IjNrBVGfSDNQU5oNz40glsVHFywt1CfURWowVQzNa"
    - repoURL: https://github.com/xela-zone/k3s.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: matrix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
