apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/xela-zone/k3s.git
    path: matrix
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: matrix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
