apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 82.2.0
    helm:
      valuesObject:
        grafana:
          grafana.ini:
            auth:
              disable_login_form: true
            auth.anonymous:
              enabled: true
              org_role: Admin
          ingress:
            enabled: true
            ingressClassName: tailscale
            annotations:
              tailscale.com/hostname: "grafana"
              tailscale.com/https: "true"
              tailscale.com/tags: "tag:deployment"
            hosts:
              - grafana.moose-amberjack.ts.net
            path: /
            pathType: Prefix
            tls:
              - hosts:
                  - grafana.moose-amberjack.ts.net
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
