apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 82.4.0
    helm:
      valuesObject:
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            resources:
              requests:
                cpu: 300m
                memory: 1600Mi
              limits:
                cpu: 500m
                memory: 2Gi
        grafana:
          resources:
            requests:
              cpu: 20m
              memory: 350Mi
            limits:
              cpu: 100m
              memory: 512Mi
          dashboards:
            default:
              longhorn:
                gnetId: 13070
                revision: 1
                datasource: Prometheus
              authentik:
                gnetId: 14514
                revision: 1
                datasource: Prometheus
          grafana.ini:
            auth:
              disable_login_form: true
            auth.anonymous:
              enabled: true
              org_role: Admin
          ingress:
            enabled: true
            ingressClassName: tailscale
            annotations:
              tailscale.com/hostname: "monitoring"
              tailscale.com/https: "true"
              tailscale.com/tags: "tag:deployment"
            hosts:
              - monitoring.moose-amberjack.ts.net
            path: /
            tls:
              - hosts:
                  - monitoring.moose-amberjack.ts.net
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true