apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: garage
  namespace: garage
spec:
  serviceName: garage-headless
  replicas: 1
  selector:
    matchLabels:
      app: garage
  template:
    metadata:
      labels:
        app: garage
    spec:
      containers:
        - name: garage
          image: dxflrs/garage:v2.2.0
          command: ["/garage"]
          args: ["-c", "/etc/garage/garage.toml", "server"]
          ports:
            - containerPort: 3900
              name: s3-api
            - containerPort: 3901
              name: rpc
            - containerPort: 3902
              name: s3-web
            - containerPort: 3903
              name: admin
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/garage/garage.toml
              subPath: garage.toml
            - name: secrets
              mountPath: /etc/garage/rpc_secret
              subPath: rpc_secret
          readinessProbe:
            httpGet:
              path: /health
              port: 3900
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: garage-data
        - name: config
          configMap:
            name: garage-config
        - name: secrets
          secret:
            secretName: garage-secrets
            defaultMode: 0400
---
apiVersion: v1
kind: Service
metadata:
  name: garage
  namespace: garage
spec:
  ports:
    - port: 3900
      name: s3-api
      targetPort: 3900
    - port: 3902
      name: s3-web
      targetPort: 3902
    - port: 3903
      name: admin
      targetPort: 3903
  selector:
    app: garage
---
apiVersion: v1
kind: Service
metadata:
  name: garage-headless
  namespace: garage
spec:
  clusterIP: None
  ports:
    - port: 3901
      name: rpc
  selector:
    app: garage
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: garage-admin
  namespace: garage
  annotations:
    tailscale.com/hostname: "garage"
    tailscale.com/https: "true"
    tailscale.com/tags: "tag:deployment"
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - garage.moose-amberjack.ts.net
  rules:
  - host: garage.moose-amberjack.ts.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: garage
            port:
              name: admin
