apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: garage-data
  namespace: longhorn-system
  labels:
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessMode: rwo
  backupBlockSize: "2097152"
  backupCompressionMethod: lz4
  backupTargetName: default
  dataEngine: v1
  frontend: blockdev
  numberOfReplicas: 1
  size: "10737418240" # 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: garage-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
    volumeHandle: garage-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data
  namespace: garage
  labels:
    # Pick up automated S3 backups
    recurring-job-group.longhorn.io/default: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
  volumeName: garage-data
