apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-ui
  namespace: garage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garage-ui
  template:
    metadata:
      labels:
        app: garage-ui
    spec:
      initContainers:
        - name: config-generator
          image: busybox
          command:
            - sh
            - -c
            - |
              cat <<EOF > /config/config.yaml
              server:
                host: "0.0.0.0"
                port: 3000
                root_url: "https://garage-ui.kbrt.xyz"
              garage:
                endpoint: "http://garage.garage.svc:3900"
                admin_endpoint: "http://garage.garage.svc:3903"
                admin_token: "$GARAGE_RPC_SECRET"
              auth:
                oidc:
                  enabled: true
                  issuer_url: "https://id.kbrt.xyz/application/o/garage-ui/"
                  client_id: "$OIDC_CLIENT_ID"
                  client_secret: "$OIDC_CLIENT_SECRET"
                  # Automatically generated redirect URL: root_url + /auth/oidc/callback
              EOF
          env:
            - name: GARAGE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: garage-secrets
                  key: rpc_secret
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: garage-secrets
                  key: oidc_client_id
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: garage-secrets
                  key: oidc_client_secret
          volumeMounts:
            - name: config-volume
              mountPath: /config
      containers:
        - name: garage-ui
          image: noooste/garage-ui:latest
          command: ["/app/garage-ui"]
          args: ["-config", "/app/config/config.yaml"]
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 30
      volumes:
        - name: config-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: garage-ui
  namespace: garage
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: http
  selector:
    app: garage-ui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: garage-ui
  namespace: garage
  annotations:
    tailscale.com/hostname: "garage-ui"
    tailscale.com/https: "true"
    tailscale.com/tags: "tag:deployment"
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - garage-ui.kbrt.xyz
  rules:
  - host: garage-ui.kbrt.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: garage-ui
            port:
              name: http