apiVersion: v1
kind: Service
metadata:
  name: cobalt-api
  namespace: alexbot
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    matchLabel:
      service: cobalt-api
