apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: cobalt-api
  name: cobalt-api
  namespace: alexbot
spec:
  selector:
    matchLabels:
      service: cobalt-api
  replicas: 1
  template:
    metadata:
      labels:
        service: cobalt-api
    spec:
      containers:
        - env:
            - name: API_URL
              value: http://cobalt-api:9000/
          image: ghcr.io/imputnet/cobalt:10
          name: cobalt-api
          ports:
            - containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
