apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: backblaze-b2-store
  namespace: alexbot
spec:
  configuration:
    destinationPath: "s3://k3s-backup-7cabee/alex-bot-database-v4/"
    endpointURL: "https://s3.us-west-004.backblazeb2.com"
    s3Credentials:
      accessKeyId:
        name: backblaze-app-key-secret
        key: username
      secretAccessKey:
        name: backblaze-app-key-secret
        key: password
    wal:
      compression: gzip
      maxParallel: 1
    data:
      compression: gzip
      jobs: 2
  retentionPolicy: "30d"
  instanceSidecarConfiguration:
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    retentionPolicyIntervalSeconds: 3600
