# alexbot/secrets.yaml
# This file defines all the secrets that the 1Password Operator should manage.

# --- Secret for the main application secrets ---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: app-secrets
  namespace: alexbot
spec:
  # Replace with the path to your app secrets item
  itemPath: "https://start.1password.com/open/i?a=O2ACK6BKVBFW7MSPHL5IATC3OY&v=ptjje7jpatl54g3y4sgwsnlyge&i=xsuy6vobegvem6nlitmjiscicy&h=my.1password.com"

---
# --- Secret for the Google Service Account JSON file ---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: google-creds
  namespace: alexbot
spec:
  # Replace with the path to your Google credentials document item
  itemPath: "https://start.1password.com/open/i?a=O2ACK6BKVBFW7MSPHL5IATC3OY&v=ptjje7jpatl54g3y4sgwsnlyge&i=epyqhxdax3cbv4remdacgd7rp4&h=my.1password.com"
